name: mi_argentina
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  auto_size_text: ^3.0.0
  intl: ^0.17.0
  flutter_swipe_action_cell: ^3.1.3
  url_launcher: ^6.0.20
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true

  assets:
    - lib/img/iconoCobros.png
    - lib/img/turnosProgramados.jpg
    - lib/img/iconoDocumentos.png
    - lib/img/iconoHijos.png
    - lib/img/iconoSalud.png
    - lib/img/iconoTrabajo.png
    - lib/img/iconoTramites.png
    - lib/img/iconoTurnos.png
    - lib/img/iconoVehiculos.png
    - lib/img/iconoArg.png
    - lib/img/logoPerfil.png
    - lib/img/menuNav.png
    - lib/img/solicitarTurno.png
    - lib/img/footerINICIO.png
    - lib/img/footerNovedades.png
    - lib/img/footerTelefonos.png
    - lib/img/footerTina.png
    - lib/img/miniDNI.png
    - lib/img/manoTelefono.png
    - lib/img/cardMINIdni.jpg
    - lib/img/cardMINIdniABIERTO.jpg
    - lib/img/cardMINIdniABIERTOsegundaparte.jpg
    - lib/img/cardMINIdniABIERTOprimeraparte.jpg
    - lib/img/headerDNIDIGITAL.jpg
    - lib/img/ingresaPIN.png
    - lib/img/headerDNI.jpg
    - lib/img/carnetAdelante.png
    - lib/img/carnetAtras.png
    - lib/img/puntoCambioA.png
    - lib/img/puntoCambioB.png
    - lib/img/datosDNI.png
    - lib/img/headerInicio.png
    - lib/img/segundaParteInicio.png
    - lib/img/terceraParteInicio.png
    - lib/img/footer.png
    - lib/img/headerVei.jpg
    - lib/img/exteriorVei.jpg
    - lib/img/nohayvei.jpg
    - lib/img/headerMiSalud.jpg
    - lib/img/cardUnoSalud.jpg
    - lib/img/cardDosSalud.png
    - lib/img/cardTresSalud.png
    - lib/img/headerMisTurnos.jpg
    - lib/img/cardParaMisTurnos.jpg
    - lib/img/headerMisCobros.jpg
    - lib/img/cardMisCobros.jpg
    - lib/img/headerMisTramites.jpg
    - lib/img/cardMisTramites.jpg
    - lib/img/headerMisHijos.jpg
    - lib/img/cardMisHijos.jpg
    - lib/img/headerMiTrabajo.jpg
    - lib/img/cardMiTrabajo.jpg
    - lib/img/PantallaCarga.jpg
    - lib/img/infoDNI.png
    - lib/img/todasTusCredenciales.png

    