name: mi_argentina
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  auto_size_text: ^3.0.0
  intl: ^0.17.0
  flutter_swipe_action_cell: ^3.1.3
  url_launcher: ^6.0.20
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true

  assets:
    - lib/img/iconoCobros.png
    - lib/img/iconoDocumentos.png
    - lib/img/iconoHijos.png
    - lib/img/iconoSalud.png
    - lib/img/iconoTrabajo.png
    - lib/img/iconoTramites.png
    - lib/img/iconoTurnos.png
    - lib/img/iconoVehiculos.png
    - lib/img/logoMiArg.png
    - lib/img/logoPerfil.png
    - lib/img/menuNav.png
    - lib/img/solicitarTurno.png
    - lib/img/footerINICIO.png
    - lib/img/footerNovedades.png
    - lib/img/footerTelefonos.png
    - lib/img/footerTina.png
    - lib/img/miniDNI.png
    - lib/img/manoTelefono.png
    - lib/img/cardMINIdni.png
    - lib/img/cardMINIdniABIERTO.png
    - lib/img/cardMINIdniSegundaParte.png
    - lib/img/cardMINIdniABIERTOprimeraparte.png
    - lib/img/headerDNIDIGITAL.png
    - lib/img/ingresaPIN.png
    - lib/img/headerDNI.png
    - lib/img/carnetAdelante.png
    - lib/img/carnetAtras.png
    - lib/img/puntoCambioA.png
    - lib/img/puntoCambioB.png
    - lib/img/datosDNI.png
    - lib/img/headerInicio.png
    - lib/img/segundaParteInicio.png
    - lib/img/terceraParteInicio.png
    - lib/img/footer.png
    - lib/img/headerVehiculos.png
    - lib/img/cardParaVehiculo.png
    - lib/img/headerMiSalud.png
    - lib/img/cardUnoSalud.png
    - lib/img/cardDosSalud.png
    - lib/img/cardTresSalud.png
    - lib/img/headerMisTurnos.png
    - lib/img/cardParaMisTurnos.png
    - lib/img/headerMisCobros.png
    - lib/img/cardMisCobros.png
    - lib/img/headerMisTramites.png
    - lib/img/cardMisTramites.png
    - lib/img/headerMisHijos.png
    - lib/img/cardMisHijos.png
    - lib/img/headerMiTrabajo.png
    - lib/img/cardMiTrabajo.png
    - lib/img/PantallaCarga.png
    - lib/img/infoDNI.png